### ISSUE TITLE
Bug in Self Enumeration

### ISSUE THREAD

**Issue by ankushgoel27** [AdnaneKhan/Gato-X#41]
**Describe the bug**
Traceback (most recent call last):
  File "/root/.local/bin/gato-x", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/main.py", line 6, in entry
    sys.exit(cli.cli(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/cli/cli.py", line 82, in cli
    arguments.func(arguments, subparsers)
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/cli/cli.py", line 330, in enumerate
    Output.write_json(exec_wrapper, args.output_json)
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/cli/output.py", line 69, in write_json
    json_out.write(json.dumps(execution_wrapper.toJSON(), indent=4))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/models/execution.py", line 55, in toJSON
    "repositories": [
                    ^
TypeError: 'NoneType' object is not iterable

**To Reproduce**
`gato-x enum -s -oJ gato.jso`

**Expected behavior**
if an error occurs, it should at least continue with rest of the repos.

**Screenshots**

** Environment (please complete the following information):**
- OS: ubuntu 
- Python Version: Python 3.12.3

**Additional context**

**Comment by AdnaneKhan** [comment]
Thanks for the bug report - I'm suspecting this happens when the user has no repositories and it is setting the list to None and failing when it tries to render the JSON.

Should have a fix for it soon!

**Comment by AdnaneKhan** [comment]
Can you check if the updates in https://github.com/AdnaneKhan/Gato-X/pull/42 fixes the issue?
