### ISSUE TITLE
Unexpected Crash while Running Enumeration

### ISSUE THREAD

**Issue by ankushgoel27** [AdnaneKhan/Gato-X#62]
**Describe the bug**

```
Traceback (most recent call last):
  File "/root/.local/bin/gato-x", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/main.py", line 6, in entry
    sys.exit(cli.cli(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/cli/cli.py", line 82, in cli
    arguments.func(arguments, subparsers)
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/cli/cli.py", line 341, in enumerate
    Output.write_json(exec_wrapper, args.output_json)
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/cli/output.py", line 69, in write_json
    json_out.write(json.dumps(execution_wrapper.toJSON(), indent=4))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/gato-x/lib/python3.12/site-packages/gatox/models/execution.py", line 55, in toJSON
    organization.toJSON() for organization in self.organizations
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'toJSON'
```

**To Reproduce**

gato-x enum -s -oJ gato.json

**Expected behavior**
should enumerate all results into gato.json file

**Screenshots**

** Environment (please complete the following information):**
- OS - ubuntu linux

**Additional context**

**Comment by AdnaneKhan** [comment]
Does the account you are testing with have any org access? Trying to reproduce it.

**Comment by AdnaneKhan** [comment]
> yes, it does have orgs. Its a one off so not sure what causing the crash. it always crashes with this particular token.

Do some of the orgs use SAML SSO, and the token isn't SAML SSO authorized to all of them? Or perhaps some other restriction where the user is an org member but they have read access 0 repos in an org.

**Comment by AdnaneKhan** [comment]
> can it do error handling and move on?

Yeah, I can definitely add that. Should have a minor version bump out this week.

**Comment by AdnaneKhan** [comment]
@ankushgoel27 can you test if `fix/self_enum_crash` addresses the issue?
